### ISSUE TITLE
How to run my own remote node for the GUI wallet? The default nodes are unreachable or too slow.

### ISSUE THREAD

**Issue by zbobyuan** [loki-project/loki-electron-gui-wallet#110]
I have lokid running in a VPS, is there a guide to make it as a remote node ?

**Comment by foomip** [comment]
Yes please, the current remote nodes are extremely unreliable. I have been unable to sync my wallet for a few days now (keeps getting stuck at 99.6% even after a rescan). 

Is something like this possible now or does it require dev work?

**Comment by KeeJef** [comment]
This is not because of the current remote nodes, its because the GUI wallet has not yet been updated after the hardfork. If you want to make transfers you will need to use the CLI wallet, which is located here https://github.com/loki-project/loki/releases/tag/v6.1.2

Or you can wait until we update the GUI wallet with the latest binaries on Monday
