### ISSUE TITLE
UX/UI Improvements

### ISSUE THREAD

**Issue by OlderNews** [loki-project/loki-electron-gui-wallet#136]
Windows 10, Version 1.3.3

Wallet versions is out of date and I understand this will not allow me to make transactions, but other users may not know this because of the following reasons: 
- Status said READY and is in bold Green
- Bottom of the GUI is green and seems to be fully synced ready to go
- Wallet Deamon says it's 100% synced

A new user would get frustrated by this and would need to research what is going on before realising their wallet version is out of date and they need to update. This is something that could possibly be displayed in the wallet:
- Status could be changed from Ready to: Update required
- Not displaying that it is 100% synced
- Not display Green, possibly red
![image](https://user-images.githubusercontent.com/42824519/82979441-657d4300-a02a-11ea-9ded-2606731cfc68.png)

**Comment by kylezs** [comment]
Solution to this in linked PR is:
- Check github to see what the latest release is
- If the latest release available is a hardfork ahead (minor version, in semver, ahead) then set the status bar to red and status to "UPDATE REQUIRED" as in screenshot:
<img width="1135" alt="Screen Shot 2020-09-04 at 1 31 19 pm" src="https://user-images.githubusercontent.com/8342557/92199686-37c25880-eebb-11ea-9945-b2dcbc7a55cb.png">

- Otherwise, show the bar as normal (syncing/scanning/ready)

**Comment by KeeJef** [comment]
Looks good
